# Generated by Django 3.1.7 on 2021-03-22 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='contest',
            new_name='content',
        ),
    ]
