# Generated by Django 3.1.7 on 2021-03-24 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0007_auto_20210324_1942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='category',
        ),
    ]
