# Generated by Django 3.1.7 on 2021-03-24 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0008_remove_question_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='readcount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
