# Generated by Django 3.1.7 on 2021-03-24 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0009_question_readcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='readcount',
            field=models.IntegerField(default=0),
        ),
    ]
