# Generated by Django 3.1.7 on 2021-03-24 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0011_readcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readcount',
            name='question',
            field=models.IntegerField(),
        ),
    ]
