# Generated by Django 3.1.7 on 2021-03-24 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0012_auto_20210324_2101'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Readcount',
        ),
    ]
