# Generated by Django 3.1.7 on 2021-03-26 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0014_auto_20210324_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('F', '자유게시판'), ('Q', '질문게시판'), ('C', '강좌게시판')], default='Q', max_length=1),
            preserve_default=False,
        ),
    ]
